language: php
php:
  - '5.6'
  - '7.1'

services:
  - mysql

before_install:
  - sudo apt-get update -qq

install:
  # general
  - sudo apt-get install -y bibutils zip
  # apache with php-fpm
  - sudo apt-get install -y apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f .travis/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf

  # configure PHP with yaz
  - sudo apt-get install -y $(phpenv version-name)-xsl $(phpenv version-name)-intl 
  - sudo apt-get install -y yaz libyaz4-dev 
  - pecl install yaz && \
  - pear install Structures_LinkedList-0.2.2 && \
  - pear install File_MARC && 
  - echo "extension = yaz.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo service apache2 restart
before_script:
  # mysql
  - mysql -e 'CREATE DATABASE bibliograph;'
  


  
      
      
      
      
