dist: trusty

addons:
  chrome: stable

language: php

php:
  - '5.4'
  - '5.6'
  - '7.1'

services:
  - mysql

before_install:
  - sudo apt-get update -qq

install:
  # general
  - sudo apt-get install -y bibutils zip
  # apache with php-fpm
  - sudo apt-get install -y apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf 2>/dev/null || true # as per https://github.com/travis-ci/travis-ci/issues/3385
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf 2>/dev/null || true
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f .travis/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf

  # configure PHP with yaz
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then sudo apt-get install -y php5-xsl php5-intl; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then sudo add-apt-repository -y ppa:ondrej/php && sudo apt-get update && sudo apt-get install -y php7.0-xsl php7.0-intl; fi  
  - sudo apt-get install -y yaz libyaz4-dev 
  - pear channel-update pear.php.net && yes $'\n' | pecl install yaz && pear install Structures_LinkedList-0.2.2 && pear install File_MARC 
  - sudo service apache2 restart

  # configure bibliograph
  - cp .travis/config/* bibliograph/bibliograph/services/config/
  - echo "all" > bibliograph/plugins.txt
  - cd bibliograph/bibliograph
  - ./generate.py source-hybrid
  - sudo ln -s bibliograph/bibliograph /var/www

before_script:
  # mysql
  - mysql -e 'CREATE DATABASE bibliograph;'
  
script:
  - echo "Done!";
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu http://localhost/bibliograph &
  - sleep 30
  - cat /tmp/bibliograph.log 



  
      
      
      
      
