dist: trusty

language: php

env:
  - JSONRPC_COMP_KEYSONLY=0

php:
  - '7.0'

services:
  - mysql

before_install:
  - echo "Installing prerequisites..."
  - sudo apt-get update -qq
  - sudo apt-get install -y bibutils zip

  # configure PHP with yaz/xsl/intl extensions
#  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then sudo apt-get install -y php5-xsl php5-intl; fi
#  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then sudo add-apt-repository -y ppa:ondrej/php && sudo apt-get update && sudo apt-get install -y php7.0-xsl php7.0-intl; fi  
#  - sudo apt-get install -y yaz libyaz4-dev
#  - pear channel-update pear.php.net && yes $'\n' | pecl install yaz && pear install Structures_LinkedList-0.2.2 && pear install File_MARC 
#  - sudo service apache2 restart
#  - if php -i | grep yaz --quiet && echo '<?php exit(function_exists("yaz_connect")?0:1);' | php ; then echo "YAZ is installed"; else echo "YAZ installation failed"; exit 1; fi;

install:
  - echo "Installing Bibliograph..."

  # build bibliograph
  - git clone --depth 1 https://github.com/qooxdoo/qooxdoo.git /home/travis/build/cboulanger/qooxdoo #ugly workaround
  - cp build-env/travis/config/* bibliograph/services/config/
  - pushd bibliograph
  - ./generate.py -I build
  - echo "all" > plugins.txt
  - popd
  
  # setup yii2 backend
  - pushd src/server
  - composer install
  - ln -s vendor/bower-assets vendor/bower
  - popd

  # done installing
  - echo "Installation scripts finished successufully."

before_script:
  # create databases and tables
  - mysql -e 'CREATE DATABASE bibliograph;'
  - mysql -e 'CREATE DATABASE tests;'
  
script:
  - echo "travis_fold:start:npm_install"
  - npm i -g npm
  - npm i -g npm
  - npm install || true
  - echo "travis_fold:end:npm_install"
  - npm link mocha
  - npm uninstall cboulanger/raptor-client
  - npm cache clean
  - npm install cboulanger/raptor-client
  - npm test