dist: trusty

addons:
  chrome: stable

language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

services:
  - mysql

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y bibutils zip
  # apache with php-fpm, since travis does not support mod_php
  - sudo apt-get install -y apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf 2>/dev/null || true # as per https://github.com/travis-ci/travis-ci/issues/3385
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf 2>/dev/null || true
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f .travis/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  # configure PHP with yaz
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then sudo apt-get install -y php5-xsl php5-intl; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then sudo add-apt-repository -y ppa:ondrej/php && sudo apt-get update && sudo apt-get install -y php7.0-xsl php7.0-intl; fi  
  - sudo apt-get install -y yaz libyaz4-dev 
  - pear channel-update pear.php.net && yes $'\n' | pecl install yaz && pear install Structures_LinkedList-0.2.2 && pear install File_MARC 
  - sudo service apache2 restart  

install:
  # build bibliograph
  - git clone https://github.com/qooxdoo/qooxdoo.git
  - cp .travis/config/* bibliograph/services/config/
  - echo "all" > plugins.txt
  - cd bibliograph
  - ./generate.py build
  - sudo ln -s bibliograph /var/www

before_script:
  # mysql
  - mysql -e 'CREATE DATABASE bibliograph;'
  
script:
  # open webapp to trigger setup 
  - google-chrome-stable --headless --disable-gpu http://localhost/bibliograph/build &
  - sleep 120
  # load webapp again to initialize gui
  - google-chrome-stable --headless --disable-gpu http://localhost/bibliograph/build#itemView.tableView!datasource.database1!modelType.reference &
  - sleep 30
  - cat /tmp/bibliograph.log 
  - sudo cat /var/log/apache2/other_vhosts_access.log | grep server.php
  - sudo cat /var/log/apache2/error.log 
  - mysqldump --database bibliograph
  - mysql -e 'USE bibliograph; SHOW TABLES;'



  
      
      
      
      
