dist: trusty
language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

services:
  - mysql
  - docker

cache:
  directories:
    - node_modules
    - $HOME/.composer/cache/files
    - src/vcslib

before_install:
  - echo "Installing prerequisites..."
  - sudo apt-get update -qq
  - sudo apt-get install -y bibutils zip
  - PHPVERSION=$(phpenv version-name)
  - sudo add-apt-repository -y ppa:ondrej/php && sudo apt-get update
  - sudo apt-get install -y php${PHPVERSION}-xsl php${PHPVERSION}-intl
# PEAR currently doesn't work
#  - sudo apt-get install -y yaz libyaz4-dev
#  - pear channel-update pear.php.net && yes $'\n' | pecl install yaz && pear install Structures_LinkedList-0.2.2 && pear install File_MARC
#  - if php -i | grep yaz --quiet && echo '<?php exit(function_exists("yaz_connect")?0:1);' | php ; then echo "YAZ is installed"; else echo "YAZ installation failed"; exit 1; fi;

install:
  - echo "travis_fold:start:npm_install"
  - echo "Installing dependencies..."
  - if [[ -f package-lock.json ]]; then rm package-lock.json; fi
#  - rm -rf node_modules
  - npm install npm@latest -g
  - npm install
  - echo "travis_fold:end:npm_install"
  - echo "Installation scripts finished successufully."

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS tests;'
  - cp install/travis/app.conf.toml src/server/config

script:
  - npm test
  - echo "travis_fold:start:logs"
  - cat src/server/runtime/logs/app.log
  - [[ -f src/server/runtime/logs/error.log ]] && cat src/server/runtime/logs/error.log
  - echo "travis_fold:end:logs"
  - npm run dist-create

deploy:
  provider: script
  script: build/script/docker-push.sh
  skip_cleanup: true
  on:
    all_branches: true
#    branch: master
