name: Bibliograph Tests

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    # see https://firefart.at/post/using-mysql-service-with-github-actions/
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: bibliograph
          MYSQL_PASSWORD: bibliograph
          MYSQL_DATABASE: tests
          MYSQL_ROOT_PASSWORD: bibliograph
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - name: Verify MariaDB connection
        env:
          DB_HOST: "127.0.0.1"
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          echo ">>> Trying to connect to MariaDB on port $DB_HOST:$DB_PORT..."
          COUNTER=0
          TIMEOUT=20
          while ! mysqladmin ping -h"$DB_HOST" -P"$DB_PORT" --silent; do
            sleep 1
            let "COUNTER+=1"
            if [[ $COUNTER == $TIMEOUT ]]; then
              echo "Could not establish a connection to MariaDB."
              exit 1;
            fi
          done

      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install Dependencies
        run: tool/env/install
      - name: Run Tests
        run: |
          export DB_PORT=${{ job.services.mariadb.ports[3306] }}
          tool/test/codeception



