name: Bibliograph Tests

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    # see https://firefart.at/post/using-mysql-service-with-github-actions/
    services:
      mysql_server:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: bibliograph
          MYSQL_PASSWORD: bibliograph
          MYSQL_DATABASE: tests
          MYSQL_ROOT_PASSWORD: bibliograph
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
      http_server:
        image: cboulanger/docker-phpfarm
        ports:
          - 8070:8070
          - 8071:8071
          - 8072:8082
          - 8073:8073
          - 8074:8074
        options: -v $HOME:/var/www:cached
    steps:
      - name: Check Services
        run: tool/env/services-test
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install Prerequisites
        run: tool/env/install
      - name: Run Tests
        run: |
          docker exec mysql_server mysql --version
          export DB_HOST_GITHUB=127.0.0.1
          export DB_PORT_GITHUB=${{ job.services.mysql_server.ports[3306] }}
          tool/test/codeception
