name: Bibliograph Tests

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      mysql_server:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: bibliograph
          MYSQL_PASSWORD: bibliograph
          MYSQL_DATABASE: tests
          MYSQL_ROOT_PASSWORD: bibliograph
        options: --name=mysql_server --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
      http_server:
        image: cboulanger/docker-phpfarm
        ports:
          - 8070:8070
          - 8071:8071
          - 8072:8072
          - 8073:8073
          - 8074:8074
        options: --name=http_server
        volumes:
          - /home/runner/work/bibliograph:/github/workspace
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Mount workspace dir into apache document root
        run: |
          docker exec http_server ln -s /github/workspace/bibliograph/{compiled,dist,src,test} /var/www
          docker exec http_server ls -al /var/www/src/client/bibliograph
          tool/dev/php test/phpversion.php
          exit 1
      - name: Check Services
        env:
          DB_HOST_GITHUB: 127.0.0.1
          DB_PORT_GITHUB: ${{ job.services.mysql_server.ports[3306] }}
        run: tool/env/services-test
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install Prerequisites
        run: tool/env/install
      - name: Run Tests
        env:
          DB_HOST_GITHUB: 127.0.0.1
          DB_PORT_GITHUB: ${{ job.services.mysql_server.ports[3306] }}
        run: tool/test/codeception
